# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='probation',
            field=models.BooleanField(),
        ),
    ]
