# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20170117_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curr',
            new_name='curriculum',
        ),
    ]
